/** @type {import("./types").Config} */
export const DEFAULT_CONFIG = {
  addActiveToHeader: false,
  addUpvotedToHeader: true,
  autoCollapseNotNew: true,
  autoHighlightNew: true,
  clickHeaderToCollapse: true,
  collapsedGroups: ['developer'],
  debug: false,
  hideAiItems: false,
  hideAiSiteRegex: `^(?:${[
    'ai\\.google\\.dev',
    'anthropic\\.com',
    'chatgpt\\.com',
    'claude\\.com',
    'developers\\.openai\\.com',
    'notebooklm\\.google\\.com',
    'openai\\.com',
    '.+\\.ai',
  ].join('|')})$`,
  hideAiTitleRegex: `\\b(?:${[
    'AGI',
    'AIs?',
    'agent(?:ic|s)?',
    'Anthropic',
    'Apple Intelligence',
    'autoresearch',
    'CharacterAI',
    'Claude',
    '\\w+claw',
    'Codex',
    'coding agents?',
    'Copilot',
    'Cowork',
    'Gas ?Town',
    'Gemini',
    'Gemma',
    'GenAI',
    '\\w*GPT',
    'GPT\\d+',
    'Gro[kq]',
    'o?llama(?:\\.?cpp)?',
    'LLMs?',
    '\\w+LLM',
    'Mistral',
    '\\w*MCP',
    // Things which maybe qualify "model"
    '(?:best|embedding|language|local|open(?:[- ]?(?:source|weight))?|small|trained|voice) models?',
    'model (?:collapse|context protocol|training)',
    'Mythos',
    'Nano Banana',
    'OpenCode',
    'OpenAI',
    'OpenRouter',
    'prompts',
    'quantization',
    'Qwen\\d*',
    'slop',
    'Sora',
    'spec[- ]?driven',
    'vibe(?:cod(?:e\\w*|ing))?',
    'vLLM',
    'xAI',
  ].join('|')})\\b`,
  hideCommentsNav: false,
  hideJobsNav: false,
  hidePastNav: false,
  hideReplyLinks: false,
  hideSubmitNav: false,
  submitTextAreaWithKeyboard: true,
  makeSubmissionTextReadable: true,
  preventAccidentally: false,
}